### ISSUE TITLE
June Meetup

### ISSUE THREAD

**Issue by nebrius** [nodebots/sf#32] opened 2015-05-06 18:16 UTC
Bike hacking with @alexglow! It's happening!

This one we will want to do in conjunction with NodeConf, since the conference was cancelled, but people are going to be in town anyways.

We can either do it (hopefully) at Pier 9 on Tuesday May 9th, following the tour that @MelanieLok is giving with the Norfolk crew, or somewhere near OaklandJS on Wednesday May 10th and try to work those in together.

My initial reaction is that I prefer the Tuesday option. There's no particular reason, just a slight gut reaction though, so I'm flexible.

**Comment by melanielok** [comment] 2015-05-13 20:18
Tuesday June 10 right?

**Comment by melanielok** [comment] 2015-05-13 20:19
Sorry.  Tuesday June 9.  What time should I ask for?

**Comment by bryan-m-hughes** [comment] 2015-05-13 20:24
@melanielok can you ask about 6 to 9 for the meetup, plus an hour before for setup?

**Comment by bryan-m-hughes** [comment] 2015-05-18 00:20
@melanielok have you had a chance to follow up with Pier 9 yet? If possible, I would like to get the meetup posted tomorrow

**Comment by MaxZoosk** [comment] 2015-05-18 17:52
Building rules have changed since last Zoosk hosted. I will need to give them a list of people attending/planning on attending this time.

**Comment by melanielok** [comment] 2015-05-19 15:24
urgh.   I'm not getting notifications from github.  Lemme reach out to them now about the date and time.

**Comment by bryan-m-hughes** [comment] 2015-05-19 16:41
Thanks @melanielok 

I hate it when I don't get notifications from GItHub. Make sure that you "watch" the repo (there's a button in the upper right). This should enable email notifications for you

**Comment by bryan-m-hughes** [comment] 2015-05-21 16:33
The meetup is live! http://www.meetup.com/nodebotssf/events/222690451/

@alexglow, does the description sound right to you?

@melanielok any updates on Pier 9?

**Comment by melanielok** [comment] 2015-05-23 17:11
No updates on Pier 9 but may have space at Amazon.

**Comment by bryan-m-hughes** [comment] 2015-05-23 20:53
Oh fun, I didn't even know Amazon had an office in SF

**Comment by melanielok** [comment] 2015-05-27 15:23
So both my contacts at pier 9 are traveling that week.  Do you want me to ask the Amazon people?

**Comment by alexglow** [comment] 2015-05-27 15:32
Hey folks, can we build in a materials cost? I want to order the LED rolls and other supplies; it would be about $10-15/person, depending on how many show up (more people, less per-capita cost). Perhaps an Eventbrite? That would help us get a gauge on "true" attendance, too :)

It definitely isn't a problem to have a lower number of attendees, and I can boost the number if needed from the Noisebridge community, who have apparently been making noise about wanting something like this.

w00t!

**Comment by alexglow** [comment] 2015-05-27 15:50
Also, thanks for setting up the events and everything!

**Comment by bryan-m-hughes** [comment] 2015-05-27 16:13
@melanielok aw, too bad about Pier 9. Please do ask at Amazon

@alexglow What do you think about finding a company to sponsor the hardware costs? I'm a little wary of charging at this point in time since people have already started to RSVP.

**Comment by melanielok** [comment] 2015-05-29 00:37
So Amazon is in. $150 for the security guy to stay late.  I can have my company cover that.

**Comment by dshaw** [comment] 2015-05-29 00:38
Awesome!



On Thursday, May 28, 2015, melanielok <notifications@github.com> wrote:

> So Amazon is in. $150 for the security guy to stay late. I can have my
> company cover that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodebots/sf/issues/32#issuecomment-106641360>.
>


-- 
Daniel Shaw
@dshaw

**Comment by alexglow** [comment] 2015-05-29 19:30
I'd love to find a company to sponsor hardware, but it's a bit down to the wire... Has there been a workshop like this before, where we need raw materials?

I'll check on some potentials. Hackster may be able to but I can't promise :)

**Comment by dshaw** [comment] 2015-05-29 19:33
20x $10-15 for materials?

**Comment by bryan-m-hughes** [comment] 2015-06-02 00:39
@alexglow We have needed raw materials in the past. The lighting workshop with Kassandra comes to mind last fall, and that was a much higher bill (around $700).

It would be awesome if Hackster could sponsor, but if not, we can ask around. @Frijol, would Tessel be interested in sponsoring? Or @skalnik, would GitHub be interested in sponsoring? It sounds like the total BOM would be ~$250.

**Comment by bryan-m-hughes** [comment] 2015-06-02 00:53
So there are some complications with Amazon. In addition to the security deposit, it doesn't look like they will sponsor food/drink either. I'm thinking we should look elsewhere.

@dshaw we haven't been to New Relic in a while. Can you introduce me to your contacts there?

**Comment by bryan-m-hughes** [comment] 2015-06-02 00:55
Oh, also, @TheAlphaNerd, what about hosting at Famo.us? Since it's not a Thursday, for once, there isn't that conflict with the event you normally have on Thursdays, right?

**Comment by Frijol** [comment] 2015-06-02 01:07
Would you like me to ask my Autodesk contacts? Not sure if they'd be on board for dinner etc but I can ask. Is that a requirement?

**Comment by bryan-m-hughes** [comment] 2015-06-02 01:13
@Frijol that would be awesome! Dinner isn't a strict requirement, but it makes our lives a lot easier since we otherwise have to handle the logistics and cost ourselves.

**Comment by Frijol** [comment] 2015-06-03 05:23
All right, asked– we'll see!

**Comment by emilyrose** [comment] 2015-06-03 05:28
this seems relevant to my interests.

**Comment by bryan-m-hughes** [comment] 2015-06-03 05:30
Thanks @Frijol! _fingers crossed_

**Comment by bryan-m-hughes** [comment] 2015-06-04 01:15
@Frijol, any word back yet?

**Comment by alexglow** [comment] 2015-06-04 03:28
I'm spending tomorrow hacking up the prototype and making sure we get all the HW in time ^_^

Hackster can't sponsor with funds (aah startup aah), but if we still need a venue, I might be able to get Geekdom!

**Comment by bryan-m-hughes** [comment] 2015-06-04 03:59
@alexglow, can you ask geekdom?

I've been asking around as well, but no luck so far.

We still have the option of doing Amazon, but that will add a few hundred to the cost, so I really want to avoid that if possible.

**Comment by Frijol** [comment] 2015-06-04 04:30
Question back from my contact: "would users post instructables?"

**Comment by bryan-m-hughes** [comment] 2015-06-04 04:42
@Frijol We haven't done that in the past, but we could maybe work that into the evening, and the NodeBots SF twitter can retweet everything posted.

@alexglow are you ok with that? Do instructables and hackster kind of overlap?

**Comment by Frijol** [comment] 2015-06-04 15:36
Still waiting to hear back from Autodesk, but I can offer the Technical Machine office if we need it. Could probably fit ~20 bikes?

We can't sponsor food or anything, but let me know

**Comment by dshaw** [comment] 2015-06-04 16:14
If we move to Technical Machines, I'll cover food.

**Comment by bryan-m-hughes** [comment] 2015-06-04 16:28
I can get behind hosting at Tessel, the garage space would make it pretty great for bringing bikes in. Distance from SF is a concern of course, but maybe we could make up for it with Oakland folks.

PubNub can host us (including food), but there's a catch. SFJS is also there that night, so they would have the main area and we would be in a back conference room.

There's a chance we can host at Rdio, I'm still working out the details on that one. It's not guaranteed.

I reached out to Maker Square, still waiting to hear back on them.

I've been thinking about it, and I think Amazon is out...it's better to cancel/postpone due to the high cost that we would have to get sponsored elsewhere (food/drink _and_ hardware _and_ security dep.)

**Comment by bryan-m-hughes** [comment] 2015-06-04 16:35
@alexglow thanks for taking care of hardware. Just to confirm, you're ordering the hardware for that night, correct?

@dshaw can NodeSource sponsor the hardware cost?

**Comment by dshaw** [comment] 2015-06-04 17:10
@bryan-m-hughes What's the damage?

**Comment by bryan-m-hughes** [comment] 2015-06-04 17:24
@alexglow ^^? IIRC $15 per @20 people was the estimate, and I think 20 sounds like a reasonable number.

Update, Rdio is looking like a real possibility actually. I'll let everyone know once it's confirmed

**Comment by dshaw** [comment] 2015-06-04 17:32
Let's bang the sponsor drum a bit more, but I can guarantee coverage so we can make the order.

**Comment by bryan-m-hughes** [comment] 2015-06-04 17:33
kk. @alexglow, can we get a BOM so we have an exact cost?

**Comment by alexglow** [comment] 2015-06-04 18:32
Awaiting response for Geekdom; looks like the night should be free...

I'm ordering the hardware, yes. Touching up the exact BoM now, will be in touch. If we can avoid an explicit Instructables connection, that'd be best since I'm taking work time to get the workshop in shape.

I *might* be able to get some Edisons from our hackathon stock, which would be fantastic! Unless Spark or PunchThrough want to jump in and sponsor. Will be in touch with an update as soon as I get that solid.

**Comment by emilyrose** [comment] 2015-06-04 18:38
@alexglow how many do we need? :smile_cat:

**Comment by bryan-m-hughes** [comment] 2015-06-04 18:38
It's official, Rdio is hosting! We even get the penthouse, which has awesome views of the city from the mission :D Food/drinks will be provided too.

**Comment by dshaw** [comment] 2015-06-04 18:39
:dancer:

**Comment by bryan-m-hughes** [comment] 2015-06-04 18:39
http://skybluepenthouse.com/

**Comment by dshaw** [comment] 2015-06-04 19:10
Wow, that's sweet.

**Comment by alexglow** [comment] 2015-06-04 19:19
That's awesome!!

Can we close admission now? It's getting quite big and we need to make sure we've got enough supplies. Thanks :)

**Comment by bryan-m-hughes** [comment] 2015-06-04 19:22
I would prefer to keep it open. Our actual attendance rate is usually about 30% of RSVP'ed attendees, which is only 10 people right now.

Last time we closed admission, we capped it at 40 people for the soldering workshop, and only 8 people showed up :(

**Comment by alexglow** [comment] 2015-06-04 19:33
TBH, charging a nominal fee tends to discourage no-shows. Depending on the amount of sponsorship we get, it could be a good move... though then again, as you mentioned, it would likely be different since the event started out being free :/

Tough call!

**Comment by bryan-m-hughes** [comment] 2015-06-04 19:36
I was chatting with some of the other JS organizers at JSConf, and a lot of them charge a small fee. I'm starting to think we should do that too for future events, but yes, too late to do it now.

NodeBots Day would be a good time to implement that, since it's kind of a different event anyways.

**Comment by emilyrose** [comment] 2015-06-04 20:09
If we decide to charge for tickets, I think we should make it very visible that we offer free tickets to those that aren't able to afford a ticket (regardless of how inexpensive).

**Comment by bryan-m-hughes** [comment] 2015-06-04 20:11
+1

**Comment by dshaw** [comment] 2015-06-04 20:50
@emilyrose Great point. With EnterpriseJS we had to make it super obvious too. (People don't read.) We state it at the top of the description, but had to add it to the RSVP link too.

Click on RSVP to see: https://enterprisejssfbay1.splashthat.com/

**Comment by alexglow** [comment] 2015-06-05 00:22
Okay so! I ordered supplies that should be enough for 20 participants, which came to $214.25, about $11 per attendee. For *smart* bike lights, we should still find a hardware sponsor; I'm trying to see if Particle Cores would work, also seeing if it's possible we might use some Edisons from the Hackster hackathon stock.

If we can get Edisons with Seeed Grove Kits, that would give us a fantastic base to start with as they include an array of sensors and things. Looking into it!

**Comment by Frijol** [comment] 2015-06-05 03:42
Has anyone reached out to PunchThrough for potential hardware sponsorship? I have a contact & [the form factor is bike-friendly](https://punchthrough.com/bean/examples/automatic-bike-lights/) :)

**Comment by bryan-m-hughes** [comment] 2015-06-05 06:33
I didn't know they were in SF actually. I don't think I've met anyone from there. @Frijol do you have some contacts there?

**Comment by Frijol** [comment] 2015-06-05 17:19
Peripherally, I have the CEO's email & could ask if he's interested. Is it useful for this bike hacking event to ask if they can donate some Blue Beans, maybe in exchange for some project writeups when we use them? @alexglow

**Comment by bryan-m-hughes** [comment] 2015-06-05 23:45
Oh, so @alexglow: We do have a stock of some microcontrollers already that would be free to use, most notably lots and lots of Arduino Unos. Not portable, but enough to get things to light up. We also have a handful of Electric Imps, and I think we have a handful of Raspberry Pis and Spark Cores as well.

**Comment by alexglow** [comment] 2015-06-09 18:35
Oh fantastic!! I can bring what I have and we will have a glorious hack day.

Also, given the potential for low attendance and variable time for building the lights themselves (I unfortunately haven't had time for a workday) – plus the relatively short workshop duration – if we need to make a follow-up day sometime to get everybody working, that's cool too. :)

This is gonna be awesome!!! I'm planning to show up at 5 this evening. There will be a friend or two (Jay and Mido) who are making some sort of documentary about hackers! Is that cool?

**Comment by bryan-m-hughes** [comment] 2015-06-09 18:46
@alexglow I'm planning on hopping over to the storage unit to get hardware around 4, so 5 sounds great! I don't think anyone will be up in the penthouse yet, so maybe stop by the Rdio office and we can go up together to start setting up?

It's totally cool if your friends stop by and interview/take pictures/film/whatever (as long as they get permission from individuals first, of course). It's not technically in the Rdio office, so there's no NDAs or anything like that involved.

I did just remember though, wasn't there some soldering that needed to be done before hand? If so, has any of that been done, and if not, what sort of soldering equipment do we need for this? We have 1 or 2 irons in NodeBots SF storage, but if we need more, we'll have to borrow them from @emilyrose.

**Comment by bryan-m-hughes** [comment] 2015-06-10 20:08
It was a great night last night! Thanks everyone!

Sorry for not getting anywhere with corporate sponsors for the hardware :( I was just completely swamped these last few days. @dshaw can you coordinate with @alexglow to get the hardware order reimbursed?

**Comment by bryan-m-hughes** [comment] 2015-06-10 20:10
Also, I got a lot of great ideas from talking with other organizers to help prevent having to scramble at the last minute like we did for this one and make the organization of events go smoother.

I'm starting on a PR, but the tl;dr is creating a template TODO checklist that we add to the top of each issue, along with due dates that go here and in a shared calendar, and making delegation of responsibilities more obvious/explicit

**Comment by dshaw** [comment] 2015-06-10 21:06
@bryan-m-hughes Yes. @alexglow dshaw@nodesource.com info on how much and how to pay.

**Comment by alexglow** [comment] 2015-06-10 21:21
Omfg, that would be amazing!! Will email you. :) Thanks @bryan-m-hughes & @dshaw & @Frijol & everyone for a marvelous time.

**Closed** 2015-06-17 05:11 UTC
